services:
  jenkins:
    image: tmsp-jenkins
    ports:
      - "8080:8080"
    build:
      context: "."
      dockerfile: "Dockerfile.jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  ssh-agent:
    # imagefile details: https://hub.docker.com/r/jenkins/ssh-agent/dockerfile
    image: jenkins/ssh-agent1
    hostname: agent_1
    build:
      context: "."
      dockerfile: "Dockerfile.agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  ssh-agent2:
    # imagefile details: https://hub.docker.com/r/jenkins/ssh-agent/dockerfile
    image: jenkins/ssh-agent2
    hostname: agent_2
    build:
      context: "."
      dockerfile: "Dockerfile.agent"
#    network_mode: "host"
    volumes:
      - /tmp:/home/jenkins/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
volumes:
  jenkins_home:
