services:
  jenkins:
    image: tmsp-jenkins
    ports:
      - "8080:8080"
    build:
      context: "."
      dockerfile: "Dockerfile.jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  ssh-agent:
    image: jenkins/ssh-agent
    restart: on-failure
volumes:
  jenkins_home:
