FROM jenkins/ssh-agent

COPY --chown=jenkins jenkins_agent_key.pub "${JENKINS_AGENT_HOME}"/.ssh/authorized_keys

USER root

RUN apt-get update && \
apt-get install --no-install-recommends -y wget iproute2 git docker-compose curl ca-certificates gnupg2 software-properties-common &&\
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable" && \
apt-get -y install docker-ce



USER ${user}
