services:
  jenkins:
    image: tmsp-jenkins
    ports:
      - "8080:8080"
    build:
      context: "."
      dockerfile: "Dockerfile.jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  ssh-agent:
    # imagefile details: https://hub.docker.com/r/jenkins/ssh-agent/dockerfile
    image: jenkins/ssh-agent
    hostname: agent_1
    restart: on-failure
  ssh-agent2:
    # imagefile details: https://hub.docker.com/r/jenkins/ssh-agent/dockerfile
    image: jenkins/ssh-agent-extend
    hostname: agent_2
    build:
      context: "."
      dockerfile: "Dockerfile.agent"
    restart: on-failure
#  cssh-agent:
#    # imagefile details: https://hub.docker.com/r/jenkins/ssh-agent/dockerfile
#    image: ssh-custom-agent
#    #    ports:
#    #      - "2222:22"
#    build:
#      context: "."
#      dockerfile: "Dockerfile.custom_agent"
#    restart: on-failure
volumes:
  jenkins_home:
