FROM jenkins/ssh-agent

COPY --chown=jenkins jenkins_agent_key.pub "${JENKINS_AGENT_HOME}"/.ssh/authorized_keys

USER root

RUN apt-get update && \
  apt-get install --no-install-recommends -y wget iproute2 git docker-compose curl

USER ${user}
