FROM jenkins/ssh-agent

COPY --chown=jenkins jenkins_agent_key.pub "${JENKINS_AGENT_HOME}"/.ssh/authorized_keys

USER root

#ssh-agent is debian based use debian (bookworm) instructions to install docker: https://docs.docker.com/engine/install/debian/
RUN apt-get update && \
apt-get install --no-install-recommends -y wget iproute2 git ca-certificates curl gnupg2 software-properties-common sshpass && \
#    # Add Docker's official GPG key:
#install -m 0755 -d /etc/apt/keyrings && \
#curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
#chmod a+r /etc/apt/keyrings/docker.asc && \
#    #Add the repository to Apt sources:
#echo \
#  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
#  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#  tee /etc/apt/sources.list.d/docker.list > /dev/null && \
#apt-get update && \
#apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


USER ${user}
